name: Deploy to cPanel

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FTP
        uses: jeevat0123/Phoenixcounselling
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html # Change this to your desired remote directory

      - name: Copy files to FTP
        run: |
          lftp -e "mirror -R app/ /public_html; bye" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
